use perturbation+cell type as the target of prediction, with primary cells as the part of the validation

# environment setup

In [1]:
!python --version

# prompt: check if a file "dummy.txt" exists in /content folder

import os


# Example usage:
flag_file_path = "/content/dummy.txt"
if os.path.exists(flag_file_path):
    print(f"environment set up complete.")
    import os, sys

    nb_path = "/content/content/notebookslib"

    sys.path.insert(0, nb_path)
    sys.path
    !ls $nb_path
else:
    print(f"setting up environment. Please wait")
    #
    import os, sys
    from google.colab import drive

    drive.mount("/content/drive")
    #
    !cp /content/drive/MyDrive/Colab\ Notebooks/notebookslib-2025.tar.gz /
    !tar -xzf /notebookslib-2025.tar.gz
    #
    import os, sys

    nb_path = "/content/content/notebookslib"

    sys.path.insert(0, nb_path)
    sys.path
    !ls $nb_path

    !rm -rf $nb_path/scvi*
    !rm -rf $nb_path/torch
    #!rm -rf $nb_path/torch-2.1.2*
    #!rm -rf $nb_path/jax*

    #!pip install torch==2.1.2 wandb louvain scvi_tools==1.1.6 torchvision jax jaxlib accelerate==1.1.0 # torch==2.3.0 torchvision==0.18.0
    !pip install torch==2.3.0 wandb louvain scvi_tools==1.1.6 torchvision torchtext accelerate==1.1.0 # torch==2.3.0 torchvision==0.18.0
    #!pip install --upgrade jax jaxlib
    !touch /content/dummy.txt

Python 3.11.11
environment set up complete.
absl						 numpy-2.1.3.dist-info
absl_py-2.1.0.dist-info				 numpy.libs
aiohappyeyeballs				 numpyro
aiohappyeyeballs-2.4.6.dist-info		 numpyro-0.17.0.dist-info
aiohttp						 nvidia
aiohttp-3.11.12.dist-info			 nvidia_cublas_cu12-12.1.3.1.dist-info
aiosignal					 nvidia_cuda_cupti_cu12-12.1.105.dist-info
aiosignal-1.3.2.dist-info			 nvidia_cuda_nvrtc_cu12-12.1.105.dist-info
anndata						 nvidia_cuda_runtime_cu12-12.1.105.dist-info
anndata-0.11.3.dist-info			 nvidia_cudnn_cu12-8.9.2.26.dist-info
array_api_compat				 nvidia_cufft_cu12-11.0.2.54.dist-info
array_api_compat-1.10.0.dist-info		 nvidia_curand_cu12-10.3.2.106.dist-info
attr						 nvidia_cusolver_cu12-11.4.5.107.dist-info
attrs						 nvidia_cusparse_cu12-12.1.0.106.dist-info
attrs-25.1.0.dist-info				 nvidia_nccl_cu12-2.20.5.dist-info
bin						 nvidia_nvjitlink_cu12-12.8.61.dist-info
cached_property-2.0.1.dist-info			 nvidia_nvtx_cu12-12.1.105.dist-info
cached_property.py				 openpyxl
cell_gears-0.0.2.dist-info			 openpyxl-3.1.5.dist-info
certifi						 optax
certifi-2025.1.31.dist-info			 optax-0.2.4.dist-info
charset_normalizer				 opt_einsum
charset_normalizer-3.4.1.dist-info		 opt_einsum-3.4.0.dist-info
chex						 orbax
chex-0.1.88.dist-info				 orbax-0.1.7.dist-info
contourpy					 orbax_checkpoint-0.11.3.dist-info
contourpy-1.3.1.dist-info			 packaging
cycler						 packaging-24.2.dist-info
cycler-0.12.1.dist-info				 pandas
datasets					 pandas-2.2.3.dist-info
datasets-2.21.0.dist-info			 patsy
dateutil					 patsy-1.0.1.dist-info
dcor						 PIL
dcor-0.6.dist-info				 pillow-11.1.0.dist-info
deprecated					 pillow.libs
Deprecated-1.2.18.dist-info			 pkg_resources
dill						 propcache
dill-0.3.8.dist-info				 propcache-0.2.1.dist-info
_distutils_hack					 protobuf-5.29.3.dist-info
distutils-precedence.pth			 pyarrow
docrep						 pyarrow-19.0.0.dist-info
docrep-0.3.2.dist-info				 __pycache__
einops						 pydot
einops-0.8.0.dist-info				 pydot-3.0.4.dist-info
etils						 pygments
etils-1.11.0.dist-info				 pygments-2.19.1.dist-info
et_xmlfile					 pylab.py
et_xmlfile-2.0.0.dist-info			 pynndescent
examples					 pynndescent-0.5.13.dist-info
filelock					 pyparsing
filelock-3.17.0.dist-info			 pyparsing-3.2.1.dist-info
flash_attn					 pyro
flash_attn-1.0.4.dist-info			 pyroapi
flash_attn_cuda.cpython-311-x86_64-linux-gnu.so  pyro_api-0.1.2.dist-info
flax						 pyro_ppl-1.9.1.dist-info
flax-0.10.2.dist-info				 python_dateutil-2.9.0.post0.dist-info
flaxlib_src					 pytorch_lightning
fontTools					 pytorch_lightning-1.9.5.dist-info
fonttools-4.56.0.dist-info			 pytz
frozenlist					 pytz-2025.1.dist-info
frozenlist-1.5.0.dist-info			 PyYAML-6.0.2.dist-info
fsspec						 requests
fsspec-2024.6.1.dist-info			 requests-2.32.3.dist-info
functorch					 rich
gears						 rich-13.9.4.dist-info
google						 scanpy
h5py						 scanpy-1.10.4.dist-info
h5py-3.12.1.dist-info				 scgpt
h5py.libs					 scgpt-0.2.1.dist-info
huggingface_hub					 scib
huggingface_hub-0.28.1.dist-info		 scib-1.1.7.dist-info
humanize					 scikit_learn-1.6.1.dist-info
humanize-4.11.0.dist-info			 scikit_learn.libs
idna						 scikit_misc-0.5.1.dist-info
idna-3.10.dist-info				 scipy
igraph						 scipy-1.15.1.dist-info
igraph-0.11.8.dist-info				 scipy.libs
igraph.libs					 seaborn
importlib_resources				 seaborn-0.13.2.dist-info
importlib_resources-6.5.2.dist-info		 session_info
include						 session_info-1.0.0.dist-info
isympy.py					 setuptools
jax						 setuptools-75.8.0.dist-info
jax-0.5.0.dist-info				 share
jaxlib						 simplejson
jaxlib-0.5.0.dist-info				 simplejson-3.19.3.dist-info
jinja2						 six-1.17.0.dist-info
jinja2-3.1.5.dist-info				 six.py
joblib						 sklearn
joblib-1.4.2.dist-info				 skmisc
kiwisolver					 statsmodels
kiwisolver-1.4.8.dist-info			 statsmodels-0.14.4.dist-info
legacy_api_wrap					 stdlib_list
legacy_api_wrap-1.4.1.dist-info			 stdlib_list-0.11.0.dist-info
leidenalg					 sympy
leidenalg-0.10.2.dist-info			 sympy-1.13.3.dist-info
leidenalg.libs					 tensorstore
LICENSE						 tensorstore-0.1.71.dist-info
lightning_fabric				 testing
lightning_utilities				 texttable-1.7.0.dist-info
lightning_utilities-0.12.0.dist-info		 texttable.py
llvmlite					 threadpoolctl-3.5.0.dist-info
llvmlite-0.44.0.dist-info			 threadpoolctl.py
markdown_it					 tlz
markdown_it_py-3.0.0.dist-info			 toolz
markupsafe					 toolz-1.0.0.dist-info
MarkupSafe-3.0.2.dist-info			 torch-2.3.0.dist-info
matplotlib					 torchgen
matplotlib-3.10.0.dist-info			 torchmetrics
mdurl						 torchmetrics-1.6.1.dist-info
mdurl-0.1.2.dist-info				 torchtext
ml_collections					 torchtext-0.18.0.dist-info
ml_collections-1.0.0.dist-info			 torchvision
ml_dtypes					 torchvision-0.18.0.dist-info
ml_dtypes-0.5.1.dist-info			 torchvision.libs
mpl_toolkits					 tqdm
mpmath						 tqdm-4.67.1.dist-info
mpmath-1.3.0.dist-info				 triton
msgpack						 triton-2.3.0.dist-info
msgpack-1.1.0.dist-info				 typing_extensions-4.12.2.dist-info
mudata						 typing_extensions.py
mudata-0.3.1.dist-info				 tzdata
multidict					 tzdata-2025.1.dist-info
multidict-6.1.0.dist-info			 umap
multipledispatch				 umap_learn-0.5.7.dist-info
multipledispatch-1.0.0.dist-info		 urllib3
_multiprocess					 urllib3-2.3.0.dist-info
multiprocess					 wrapt
multiprocess-0.70.16.dist-info			 wrapt-1.17.2.dist-info
natsort						 xxhash
natsort-8.4.0.dist-info				 xxhash-3.5.0.dist-info
nest_asyncio-1.6.0.dist-info			 _yaml
nest_asyncio.py					 yaml
networkx					 yarl
networkx-3.4.2.dist-info			 yarl-1.18.3.dist-info
numba						 zipp
numba-0.61.0.dist-info				 zipp-3.21.0.dist-info
numpy

**Need to restart environment here**

# importing

In [ ]:
import copy
import gc
import json
import os
from pathlib import Path
import sys
import time
import traceback
from typing import List, Tuple, Dict, Union, Optional
import warnings
import random

import torch
from anndata import AnnData
import scanpy as sc
import numpy as np

# import scvi
import wandb
from scipy.sparse import issparse
import matplotlib.pyplot as plt
from torch import nn
from torch.nn import functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from torchtext.vocab import Vocab
from torchtext._torchtext import (
    Vocab as VocabPybind,
)

:

In [3]:
sys.path.insert(0, "../")
import scgpt as scg
from scgpt.model import TransformerModel, AdversarialDiscriminator
from scgpt.tokenizer import tokenize_and_pad_batch, random_mask_value
from scgpt.tokenizer.gene_tokenizer import GeneVocab
from scgpt.loss import (
    masked_mse_loss,
    masked_relative_error,
    criterion_neg_log_bernoulli,
)
from scgpt.preprocess import Preprocessor
from scgpt import SubsetsBatchSampler
from scgpt.utils import set_seed, eval_scib_metrics, load_pretrained

sc.set_figure_params(figsize=(4, 4))
os.environ["KMP_WARNINGS"] = "off"
warnings.filterwarnings("ignore")

/content/content/notebookslib/scgpt/model/model.py:21: UserWarning: flash_attn is not installed
  warnings.warn("flash_attn is not installed")
/content/content/notebookslib/scgpt/model/multiomic_model.py:19: UserWarning: flash_attn is not installed
  warnings.warn("flash_attn is not installed")

In [4]:
import scvi

# Step 2: use pertTF github

In [5]:
!git clone https://github.com/davidliwei/pertTF.git

Cloning into 'pertTF'...
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 194 (delta 110), reused 90 (delta 43), pack-reused 0 (from 0)
Receiving objects: 100% (194/194), 48.81 KiB | 757.00 KiB/s, done.
Resolving deltas: 100% (110/110), done.

In [6]:
sys.path.insert(0, "/content/pertTF/")

from perttf.model.pertTF import PerturbationTFModel
from perttf.model.config_gen import generate_config
from perttf.model.train_data_gen import produce_training_datasets
from perttf.model.train_function import train, wrapper_train, eval_testdata

# Step 3: hyperparameter set up

In [7]:
hyperparameter_defaults = dict(
    seed=42,
    # dataset_name="PBMC_10K", # Dataset name
    dataset_name="pancreatic",
    do_train=True,  # Flag to indicate whether to do update model parameters during training
    # load_model="/content/drive/MyDrive/Colab Notebooks/scGPT/pretrain_blood", # Path to pre-trained model
    load_model=None,
    GEPC=True,  # Gene expression modelling for cell objective
    ecs_thres=0.7,  # Elastic cell similarity objective, 0.0 to 1.0, 0.0 to disable
    dab_weight=0.0,  # 2000.0, # DAR objective weight for batch correction; if has batch, set to 1.0
    this_weight=1.0,  # weight for predicting the expression of current cell
    next_weight=00.0,  # weight for predicting the next cell
    n_rounds=1,  # number of rounds for generating the next cell
    next_cell_pred_type="identity",  # the method to predict the next cell, either "pert" (random next cell within the same cell type) or "identity" (the same cell). If "identity", set next_weight=0
    #
    ecs_weight=1.0,  # weight for predicting the similarity of cells
    cell_type_classifier=True,  #  do we need the trasnformer to separate cell types?
    cell_type_classifier_weight=1.0,
    perturbation_classifier_weight=10.0,
    perturbation_input=False,  # use perturbation as input?
    CCE=False,  # Contrastive cell embedding objective
    mask_ratio=0.15,  # Default mask ratio
    epochs=100,  # Default number of epochs for fine-tuning
    n_bins=51,  # Default number of bins for value binning in data pre-processing
    # lr=1e-4, # Default learning rate for fine-tuning
    lr=1e-3,  # learning rate for learning de novo
    batch_size=32,  # Default batch size for fine-tuning
    layer_size=32,  # defalut 32
    nlayers=2,
    nhead=4,  # if load model, batch_size, layer_size, nlayers, nhead will be ignored
    dropout=0.4,  # Default dropout rate during model fine-tuning
    schedule_ratio=0.99,  # Default rate for learning rate decay
    save_eval_interval=5,  # Default model evaluation interval
    log_interval=100,  # Default log interval
    fast_transformer=True,  # Default setting
    pre_norm=False,  # Default setting
    amp=True,  # # Default setting: Automatic Mixed Precision
    do_sample_in_train=False,  # sample the bernoulli in training
    ADV=False,  # Adversarial training for batch correction
    adv_weight=10000,
    adv_E_delay_epochs=2,  # delay adversarial training on encoder for a few epochs
    adv_D_delay_epochs=2,
    lr_ADV=1e-3,  # learning rate for discriminator, used when ADV is True
    DSBN=False,  # True if (config.dab_weight >0 or config.ADV ) else False  # Domain-spec batchnorm; default is True
    per_seq_batch_sample=False,  # DSBN # default True
    use_batch_label=False,  # default: equal to DSBN
    schedule_interval=1,
    explicit_zero_prob=True,  # whether explicit bernoulli for zeros
    n_hvg=3000,  # number of highly variable genes
    mask_value=-1,
    pad_value=-2,
    pad_token="<pad>",
)

wandb configuration

In [8]:
os.environ["WANDB_API_KEY"] = "ebbd6ca0c8ce4d7052af32e9bd74fa8fc64a2a3e"

In [9]:
config, run_session = generate_config(hyperparameter_defaults, wandb_mode="online")

wandb: Currently logged in as: li-david-wei (li-david-wei-children-s-national-hospital) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

{'seed': 42, 'dataset_name': 'pancreatic', 'do_train': True, 'load_model': None, 'GEPC': True, 'ecs_thres': 0.7, 'dab_weight': 0.0, 'this_weight': 1.0, 'next_weight': 0.0, 'n_rounds': 1, 'next_cell_pred_type': 'identity', 'ecs_weight': 1.0, 'cell_type_classifier': True, 'cell_type_classifier_weight': 1.0, 'perturbation_classifier_weight': 10.0, 'perturbation_input': False, 'CCE': False, 'mask_ratio': 0.15, 'epochs': 100, 'n_bins': 51, 'lr': 0.001, 'batch_size': 32, 'layer_size': 32, 'nlayers': 2, 'nhead': 4, 'dropout': 0.4, 'schedule_ratio': 0.99, 'save_eval_interval': 5, 'log_interval': 100, 'fast_transformer': True, 'pre_norm': False, 'amp': True, 'do_sample_in_train': False, 'ADV': False, 'adv_weight': 10000, 'adv_E_delay_epochs': 2, 'adv_D_delay_epochs': 2, 'lr_ADV': 0.001, 'DSBN': False, 'per_seq_batch_sample': False, 'use_batch_label': False, 'schedule_interval': 1, 'explicit_zero_prob': True, 'n_hvg': 3000, 'mask_value': -1, 'pad_value': -2, 'pad_token': '<pad>', 'special_tokens': ['<pad>', '<cls>', '<eoc>'], 'max_seq_len': 3001}

In [10]:
# the following parameters have been moved to config
# DSBN =False # True if (config.dab_weight >0 or config.ADV ) else False  # Domain-spec batchnorm; default is True
# per_seq_batch_sample =  False # DSBN # default True


dataset_name = config.dataset_name
save_dir = Path(f"./save/dev_{dataset_name}-{time.strftime('%b%d-%H-%M')}/")
save_dir.mkdir(parents=True, exist_ok=True)
print(f"save to {save_dir}")
logger = scg.logger
scg.utils.add_file_handler(logger, save_dir / "run.log")

save to save/dev_pancreatic-Feb25-15-48

In [11]:
# embsize = config.layer_size
# nhead = config.nhead
# nlayers = config.nlayers
# d_hid = config.layer_size

# step 4: load scrna-seq dataset

In [12]:
adata0 = sc.read_h5ad(
    "/content/drive/MyDrive/Colab Notebooks/scGPT/pancreatic/data/D18_diabetes_merged.h5ad"
)
# adata0=sc.read_h5ad("/content/drive/MyDrive/Colab Notebooks/scGPT/pancreatic/data/D18_diabetes_merged_reduced.h5ad")
adata0.layers["GPTin"] = adata0.X.copy()

In [13]:
# set up the preprocessor, use the args to config the workflow


preprocessor = Preprocessor(
    use_key="GPTin",  # the key in adata.layers to use as raw data
    # filter_gene_by_counts=3,  # step 1
    # filter_cell_by_counts=False,  # step 2
    normalize_total=None,  # 3. whether to normalize the raw data and to what sum
    # result_normed_key="X_normed",  # the key in adata.layers to store the normalized data
    log1p=False,  # 4. whether to log1p the normalized data
    # result_log1p_key="X_log1p",
    subset_hvg=False,  # 5. whether to subset the raw data to highly variable genes; use n_hvg default
    hvg_flavor="seurat_v3",  # if data_is_raw else "cell_ranger",
    binning=config.n_bins,  # 6. whether to bin the raw data and to what number of bins
    # binning=0,  # 6. whether to bin the raw data and to what number of bins
    result_binned_key="X_binned",  # the key in adata.layers to store the binned data
)
preprocessor(adata0, batch_key=None)

scGPT - INFO - Binning data ...

In [14]:
# this is for integration training
if False:
    adata = adata0[
        (adata0.obs["batch"] == 0) | (adata0.obs["Diabetes_status"] == "Non-diabetic"),
        :,
    ]

    # remove unknown cell type
    adata = adata[adata.obs["celltype"] != "unknown", :]
    # only test cells where two batches share the same cell type

    adata = adata[adata.obs["celltype"].isin(["SC-beta", "SC-alpha", "SC-delta"]), :]


if True:
    adata0.obs.loc[adata0.obs["genotype"].isna(), "genotype"] = "WT"
    adata = adata0[adata0.obs["batch"] == 0, :]  # only use cell line data for training
    adata_prim = adata0[
        adata0.obs["batch"] == 1, :
    ]  # a separate primary data as a validation data
    # prompt: randomly select 1000 n_obs from adata_prim

    import random

    random_indices = random.sample(range(adata_prim.n_obs), min(3000, adata_prim.n_obs))
    adata_prim = adata_prim[random_indices]
    adata_prim
adata

View of AnnData object with n_obs × n_vars = 31293 × 3354
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'gene', 'sgrna', 'umi_count', 'nCount_sgRNA', 'nFeature_sgRNA', 'nCount_sgRNA_guides', 'nFeature_sgRNA_guides', 'percent.mt', 'RNA_snn_res.0.5', 'seurat_clusters', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'celltype', 'genotype', 'sub.cluster', 'celltype_1', 'celltype.genotype', 'celltype_2', 'SC.alpha.PS', 'Ductal.PS', 'Endocrine.precursor.PS', 'Liver.PS', 'SC.beta.PS', 'SC.delta.PS', 'SC.EC.PS', 'Stromal.PS', 'percent_mito', 'n_counts', 'log10_n_counts', 'log_n_counts', 'n_genes', 'log10_n_genes', 'diabetes_batch', 'donor', 'leiden', 'Diabetes_status', 'batch'
    obsm: 'X_pca', 'X_umap', 'bin_edges'
    layers: 'GPTin', 'X_binned'

In [15]:
adata_prim

View of AnnData object with n_obs × n_vars = 3000 × 3354
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'gene', 'sgrna', 'umi_count', 'nCount_sgRNA', 'nFeature_sgRNA', 'nCount_sgRNA_guides', 'nFeature_sgRNA_guides', 'percent.mt', 'RNA_snn_res.0.5', 'seurat_clusters', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'celltype', 'genotype', 'sub.cluster', 'celltype_1', 'celltype.genotype', 'celltype_2', 'SC.alpha.PS', 'Ductal.PS', 'Endocrine.precursor.PS', 'Liver.PS', 'SC.beta.PS', 'SC.delta.PS', 'SC.EC.PS', 'Stromal.PS', 'percent_mito', 'n_counts', 'log10_n_counts', 'log_n_counts', 'n_genes', 'log10_n_genes', 'diabetes_batch', 'donor', 'leiden', 'Diabetes_status', 'batch'
    obsm: 'X_pca', 'X_umap', 'bin_edges'
    layers: 'GPTin', 'X_binned'

In [16]:
adata.obs.Diabetes_status.value_counts(dropna=False)

Diabetes_status
NaN    31293
Name: count, dtype: int64

In [17]:
adata.obs["genotype"].value_counts(dropna=False)

genotype
PDX1         4151
WT           4086
NEUROD1      2715
FOXA1        2629
MNX1         2294
NKX6-1       1838
TLE3         1791
PROSER1      1151
NKX2-2        948
TADA2B        909
RFX6          697
BCOR          630
PDX1het       619
PAX6          595
HNF4A         593
ARX           577
OTUD5         550
GATA4het      481
PBX1          424
ONECUT1e      414
GATA6het      357
FOXA2         330
QSER1         308
NANOGe        306
GSC           300
TET1/2/3      273
TET1          263
BMPR1A        212
GATA4         167
NGN3          164
QSER1TET1     151
HHEXe         137
GATA6          94
UBA6           62
GLIS3          46
HHEX           20
HHEXhet         6
KDM2B           5
Name: count, dtype: int64

In [18]:
adata.obs["genotype"].value_counts(dropna=False)

genotype
PDX1         4151
WT           4086
NEUROD1      2715
FOXA1        2629
MNX1         2294
NKX6-1       1838
TLE3         1791
PROSER1      1151
NKX2-2        948
TADA2B        909
RFX6          697
BCOR          630
PDX1het       619
PAX6          595
HNF4A         593
ARX           577
OTUD5         550
GATA4het      481
PBX1          424
ONECUT1e      414
GATA6het      357
FOXA2         330
QSER1         308
NANOGe        306
GSC           300
TET1/2/3      273
TET1          263
BMPR1A        212
GATA4         167
NGN3          164
QSER1TET1     151
HHEXe         137
GATA6          94
UBA6           62
GLIS3          46
HHEX           20
HHEXhet         6
KDM2B           5
Name: count, dtype: int64

In [19]:
adata.obs

,orig.ident,nCount_RNA,nFeature_RNA,gene,sgrna,umi_count,nCount_sgRNA,nFeature_sgRNA,nCount_sgRNA_guides,nFeature_sgRNA_guides,...,n_counts,log10_n_counts,log_n_counts,n_genes,log10_n_genes,diabetes_batch,donor,leiden,Diabetes_status,batch
EC1_AAACCCAAGAAGTCCG-1,Sample_L_1_3DEC,12089.0,4199.0,75_TLE3,75_TLE3,79.0,79.0,1.0,79.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
EC1_AAACCCAAGATAGTGT-1,Sample_L_1_3DEC,6601.0,2953.0,27_GATA4,27_GATA4,55.0,55.0,1.0,55.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
EC1_AAACCCACACCTCGTT-1,Sample_L_1_3DEC,11164.0,3944.0,110_WT,110_WT,399.0,399.0,1.0,399.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
EC1_AAACCCACACGGCGTT-1,Sample_L_1_3DEC,8629.0,3534.0,103_MNX1,103_MNX1,63.0,63.0,1.0,63.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
EC1_AAACCCACAGCTTCGG-1,Sample_L_1_3DEC,6410.0,2949.0,91_NKX6-1,91_NKX6-1,10.0,10.0,1.0,10.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
EC2_TTTGTTGTCACTTGGA-1,Sample_L_2_3DEC,16919.0,5791.0,112_PDX1,112_PDX1,28.0,28.0,1.0,28.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
EC2_TTTGTTGTCCTGTAAG-1,Sample_L_2_3DEC,11894.0,4354.0,91_NKX6-1,91_NKX6-1,351.0,351.0,1.0,351.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
EC2_TTTGTTGTCTCCATAT-1,Sample_L_2_3DEC,6973.0,3238.0,115_PDX1,115_PDX1,54.0,54.0,1.0,54.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
EC2_TTTGTTGTCTGATGGT-1,Sample_L_2_3DEC,8516.0,3635.0,75_TLE3,75_TLE3,46.0,46.0,1.0,46.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
EC2_TTTGTTGTCTGTGCGG-1,Sample_L_2_3DEC,1494.0,937.0,100_PAX6,100_PAX6,11.0,11.0,1.0,11.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [20]:
# for debugging only; use top 2k genes only
if False:
    value_x = raw_data_f[3, :].toarray()
    value_y = adata.X[3, :]
    # prompt: calculate and plot the correlation between value_x and value_y

    import numpy as np
    import matplotlib.pyplot as plt

    # Assuming value_x and value_y are defined as in the provided code
    # Replace with your actual data if needed

    correlation = np.corrcoef(value_x, value_y)[0, 1]
    print(f"Correlation between value_x and value_y: {correlation}")

    plt.scatter(value_x, value_y)
    plt.xlabel("value_x")
    plt.ylabel("value_y")
    plt.title(f"Correlation: {correlation:.2f}")
    plt.show()

In [21]:
set(adata.obs["genotype"])

{'ARX',
 'BCOR',
 'BMPR1A',
 'FOXA1',
 'FOXA2',
 'GATA4',
 'GATA4het',
 'GATA6',
 'GATA6het',
 'GLIS3',
 'GSC',
 'HHEX',
 'HHEXe',
 'HHEXhet',
 'HNF4A',
 'KDM2B',
 'MNX1',
 'NANOGe',
 'NEUROD1',
 'NGN3',
 'NKX2-2',
 'NKX6-1',
 'ONECUT1e',
 'OTUD5',
 'PAX6',
 'PBX1',
 'PDX1',
 'PDX1het',
 'PROSER1',
 'QSER1',
 'QSER1TET1',
 'RFX6',
 'TADA2B',
 'TET1',
 'TET1/2/3',
 'TLE3',
 'UBA6',
 'WT'}

In [22]:
adata.obs["celltype"].value_counts(dropna=False)

celltype
Ductal                 10539
SC-EC                   6380
SC-alpha                4343
SC-beta                 4174
Endocrine precursor     2933
Stromal                 1825
SC-delta                 816
Liver                    283
Name: count, dtype: int64

In [23]:
adata.obs["genotype"].value_counts(dropna=False)

genotype
PDX1         4151
WT           4086
NEUROD1      2715
FOXA1        2629
MNX1         2294
NKX6-1       1838
TLE3         1791
PROSER1      1151
NKX2-2        948
TADA2B        909
RFX6          697
BCOR          630
PDX1het       619
PAX6          595
HNF4A         593
ARX           577
OTUD5         550
GATA4het      481
PBX1          424
ONECUT1e      414
GATA6het      357
FOXA2         330
QSER1         308
NANOGe        306
GSC           300
TET1/2/3      273
TET1          263
BMPR1A        212
GATA4         167
NGN3          164
QSER1TET1     151
HHEXe         137
GATA6          94
UBA6           62
GLIS3          46
HHEX           20
HHEXhet         6
KDM2B           5
Name: count, dtype: int64

In [24]:
adata.obs.loc[adata.obs["batch"] == 0, "celltype"].value_counts(dropna=False)

celltype
Ductal                 10539
SC-EC                   6380
SC-alpha                4343
SC-beta                 4174
Endocrine precursor     2933
Stromal                 1825
SC-delta                 816
Liver                    283
Name: count, dtype: int64

In [25]:
adata.obs.loc[adata.obs["batch"] == 1, "celltype"].value_counts(dropna=False)

celltype
Ductal                 0
Endocrine precursor    0
Liver                  0
SC-EC                  0
SC-alpha               0
SC-beta                0
SC-delta               0
Stromal                0
Name: count, dtype: int64

In [26]:
adata.obs.loc[adata.obs["batch"] == 0, "genotype"].value_counts(dropna=False)

genotype
PDX1         4151
WT           4086
NEUROD1      2715
FOXA1        2629
MNX1         2294
NKX6-1       1838
TLE3         1791
PROSER1      1151
NKX2-2        948
TADA2B        909
RFX6          697
BCOR          630
PDX1het       619
PAX6          595
HNF4A         593
ARX           577
OTUD5         550
GATA4het      481
PBX1          424
ONECUT1e      414
GATA6het      357
FOXA2         330
QSER1         308
NANOGe        306
GSC           300
TET1/2/3      273
TET1          263
BMPR1A        212
GATA4         167
NGN3          164
QSER1TET1     151
HHEXe         137
GATA6          94
UBA6           62
GLIS3          46
HHEX           20
HHEXhet         6
KDM2B           5
Name: count, dtype: int64

In [27]:
adata.obs.loc[adata.obs["batch"] == 1, "genotype"].value_counts(dropna=False)

genotype
ARX          0
BCOR         0
BMPR1A       0
FOXA1        0
FOXA2        0
GATA4        0
GATA4het     0
GATA6        0
GATA6het     0
GLIS3        0
GSC          0
HHEX         0
HHEXe        0
HHEXhet      0
HNF4A        0
KDM2B        0
MNX1         0
NANOGe       0
NEUROD1      0
NGN3         0
NKX2-2       0
NKX6-1       0
ONECUT1e     0
OTUD5        0
PAX6         0
PBX1         0
PDX1         0
PDX1het      0
PROSER1      0
QSER1        0
QSER1TET1    0
RFX6         0
TADA2B       0
TET1         0
TET1/2/3     0
TLE3         0
UBA6         0
WT           0
Name: count, dtype: int64

# step 5: preprocess dataset

In [28]:
# process the batch separately
# not needed, because the normalization is for each cell
# adata_batch0.layers['X_binned'][3,:].max()#
# adata=adata_batch0.concatenate(adata_batch1)

# adata.layers['GPTin'].toarray()

In [29]:
# adata.obs['batch_id'].value_counts(dropna=False)

Tokenize the input data for model fine-tuning

In [30]:
data_produced = produce_training_datasets(adata, config)

# cell_type_to_index=data_produced['cell_type_to_index']
# genotype_to_index=data_produced['genotype_to_index']


# num_batch_types=data_produced['num_batch_types']
# n_perturb=data_produced['n_perturb']
# n_cls=data_produced['n_cls']

scGPT - INFO - train set number of samples: 28163,
	 feature length: 3001
scGPT - INFO - valid set number of samples: 3130,
	 feature length: 3001

save data

In [31]:
# adata.obs['is_in_training']=adata.obs.index.isin(data_produced['cell_ids_train'])
adata0.obs["is_in_training"] = adata0.obs.index.isin(data_produced["cell_ids_train"])
# sum(adata.obs['is_in_training'])
adata0.write_h5ad(save_dir / f"adata_original_full.h5ad")

In [32]:
# train_data.shape

 # Step 6: Build or Load the pre-trained scGPT model

In [33]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

vocab = data_produced["vocab"]

ntokens = len(vocab)  # size of vocabulary
model = PerturbationTFModel(
    data_produced["n_perturb"],  # n_perturb, # number of perturbation labels
    3,  # layers
    ntokens,
    config.layer_size,  # embsize,
    config.nhead,  # nhead,
    config.layer_size,  # d_hid,
    config.nlayers,  # nlayers,
    vocab=vocab,
    dropout=config.dropout,
    pad_token=config.pad_token,
    pad_value=config.pad_value,
    do_mvc=config.GEPC,
    do_dab=True if config.dab_weight > 0 else False,
    use_batch_labels=config.use_batch_label,
    num_batch_labels=data_produced["num_batch_types"],  # num_batch_types,
    domain_spec_batchnorm=config.DSBN,
    n_input_bins=config.n_bins,
    ecs_threshold=config.ecs_thres,
    explicit_zero_prob=config.explicit_zero_prob,
    use_fast_transformer=config.fast_transformer,
    pre_norm=config.pre_norm,
    n_cls=data_produced["n_cls"],  # n_cls, # number of cell type labels
    nlayers_cls=3,
)

In [34]:
if config.load_model is not None:
    load_pretrained(model, torch.load(model_file), verbose=False)

model.to(device)
wandb.watch(model)

In [35]:
print(model)

PerturbationTFModel(
  (encoder): GeneEncoder(
    (embedding): Embedding(3357, 32, padding_idx=3354)
    (enc_norm): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
  )
  (value_encoder): ContinuousValueEncoder(
    (dropout): Dropout(p=0.4, inplace=False)
    (linear1): Linear(in_features=1, out_features=32, bias=True)
    (activation): ReLU()
    (linear2): Linear(in_features=32, out_features=32, bias=True)
    (norm): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
  )
  (transformer_encoder): TransformerEncoder(
    (layers): ModuleList(
      (0-1): 2 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=32, out_features=32, bias=True)
        )
        (linear1): Linear(in_features=32, out_features=32, bias=True)
        (dropout): Dropout(p=0.4, inplace=False)
        (linear2): Linear(in_features=32, out_features=32, bias=True)
        (norm1): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.4, inplace=False)
        (dropout2): Dropout(p=0.4, inplace=False)
      )
    )
  )
  (decoder): ExprDecoder(
    (fc): Sequential(
      (0): Linear(in_features=32, out_features=32, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=32, out_features=32, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=32, out_features=1, bias=True)
    )
    (zero_logit): Sequential(
      (0): Linear(in_features=32, out_features=32, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=32, out_features=32, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=32, out_features=1, bias=True)
    )
  )
  (cls_decoder): ClsDecoder(
    (_decoder): ModuleList(
      (0): Linear(in_features=32, out_features=32, bias=True)
      (1): ReLU()
      (2): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
      (3): Linear(in_features=32, out_features=32, bias=True)
      (4): ReLU()
      (5): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
    )
    (out_layer): Linear(in_features=32, out_features=8, bias=True)
  )
  (mvc_decoder): MVCDecoder(
    (gene2query): Linear(in_features=32, out_features=32, bias=True)
    (query_activation): Sigmoid()
    (W): Linear(in_features=32, out_features=32, bias=False)
    (W_zero_logit): Linear(in_features=32, out_features=32, bias=True)
  )
  (sim): Similarity(
    (cos): CosineSimilarity()
  )
  (creterion_cce): CrossEntropyLoss()
  (pert_encoder): PertLabelEncoder(
    (embedding): Embedding(38, 32, padding_idx=2)
    (enc_norm): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
  )
  (pert_exp_encoder): PertExpEncoder(
    (fc): Sequential(
      (0): Linear(in_features=64, out_features=32, bias=True)
      (1): Sigmoid()
      (2): Linear(in_features=32, out_features=32, bias=True)
    )
  )
  (pert_decoder): PerterbationDecoder(
    (_decoder): ModuleList(
      (0): Linear(in_features=32, out_features=32, bias=True)
      (1): ReLU()
      (2): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
      (3): Linear(in_features=32, out_features=32, bias=True)
      (4): ReLU()
      (5): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
    )
    (out_layer): Linear(in_features=32, out_features=38, bias=True)
  )
  (batch2_encoder): Batch2LabelEncoder(
    (embedding): Embedding(2, 32)
    (enc_norm): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
  )
)

# Step 7: train

In [36]:
if config.per_seq_batch_sample:
    adata_prim_v = adata_prim[adata_prim.obs["batch_id"].argsort()].copy()
else:
    adata_prim_v = adata_prim.copy()
eval_adata_dict = {
    "validation": data_produced["adata_sorted"],
    "primary": adata_prim_v,
}

In [37]:
best_model = wrapper_train(
    model, config, data_produced, eval_adata_dict=eval_adata_dict
)

Output hidden; open in https://colab.research.google.com to view.

In [38]:
if False:
    ret_adata = results["adata"]
    ret_adata.obsm["X_pert_pred"].shape
    genotype_to_index

    import numpy as np

    # Assuming ret_adata.obsm['X_pert_pred'] is a numpy array or can be converted to one
    logits = ret_adata.obsm["X_pert_pred"]

    # Convert logits to probabilities using softmax
    X_pert_pred_probs = np.exp(logits) / np.sum(np.exp(logits), axis=1, keepdims=True)

    # Assign the probabilities back to the AnnData object
    ret_adata.obsm["X_pert_pred_probs"] = X_pert_pred_probs

    # prompt: convert X_pert_pred_probs, which is the probabilities of each label, into label predictions, whose order is defined in genotype_to_index

    # Convert probabilities to predicted labels
    label_predictions = np.argmax(X_pert_pred_probs, axis=1)

    # Map predicted indices back to genotypes using genotype_to_index
    # Assuming genotype_to_index is a dictionary where keys are indices and values are genotypes
    index_to_genotype = {v: k for k, v in genotype_to_index.items()}
    predicted_genotypes = [index_to_genotype[i] for i in label_predictions]

    # Add the predicted genotypes to the AnnData object
    ret_adata.obs["predicted_genotype"] = predicted_genotypes

In [39]:
# ret_adata=results_p['adata']
# ret_adata.obs[['Diabetes_status','predicted_genotype']].value_counts(dropna=False)

In [40]:
# ret_adata.obs

In [41]:
# sc.pl.umap( ret_adata,color=["celltype"])

In [42]:
# sc.pl.umap( ret_adata,color=["predicted_genotype"])

In [43]:
# adata_prim.obs['celltype'].isin(cell_type_to_index)

In [44]:
# adata_prim.obs['genotype'].value_counts(dropna=False)

In [45]:
# adata_prim.obs.columns

In [46]:
artifact = wandb.Artifact(f"best_model", type="model")
glob_str = os.path.join(save_dir, "best_model.pt")
artifact.add_file(glob_str)
run_session.log_artifact(artifact)

run_session.finish()
wandb.finish()
gc.collect()

ValueError: Path is not a file: 'save/dev_pancreatic-Feb25-15-48/best_model.pt'

In [ ]:
# save the best model
# already incorporated into wrapper_train
if False:
    torch.save(best_model.state_dict(), save_dir / "best_model.pt")
    torch.save(vocab, save_dir / "vocab.pt")
    running_parameters = {
        "cell_type_to_index": data_produced["cell_type_to_index"],
        "genotype_to_index": data_produced["genotype_to_index"],
        "genes": data_produced["genes"],  # genes,
        "gene_ids": data_produced["gene_ids"],  # gene_ids,
    }
    running_parameters

    torch.save(running_parameters, save_dir / "running_parameters.pt")

# save the dataset
# torch.save(adata, save_dir / "adata.pt")
# torch.save(tokenized_train, save_dir / "tokenized_train.pt")
# torch.save(tokenized_valid, save_dir / "tokenized_valid.pt")
# torch.save(tokenized_train_next, save_dir / "tokenized_train_next.pt")
# torch.save(tokenized_valid_next, save_dir / "tokenized_valid_next.pt")

In [ ]:
# results['celltype_umap'].savefig(save_dir / f"test.png", dpi=300,bbox_inches='tight')

In [ ]:
!cp -r $save_dir /content/drive/MyDrive/Colab\ Notebooks/scGPT/pancreatic/